### PR TITLE
tech(common): multi line log utility added

### LINKED ISSUE #9: Add multi-line console log utility
Create a utility to support multiline console log statements with Template Literals.

The utility takes an,

Parameter - Array (`lines`)

Each line object will contain -
```
- content - The text or literal content.
- noOfTrailingNewLines - Number of new lines at the end of the line.
```
Return - print multiline

### PR DESCRIPTION
**Pull request by shangan23**
#9 

Added multi-line log utility to support multi-line console output.

### CODE REVIEW

**Comment by ramsunvtech** [comment]
@shangan23 can we squash the commits to one. seems like second one is duplicate

**Comment by shangan23** [comment]
I tried to squash but I’m getting merge error. E need to look into it
tomorrow

**Comment by shangan23** [comment]
> @shangan23 can we squash the commits to one. seems like second one is duplicate

done

**Comment by ramsunvtech** [comment]
lgtm 👍

**Review by ramsunvtech — APPROVED** [review]

**Pull request merged**
